# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dptGUI2.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(801, 650)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
#        self.mainGraphicsView = QtWidgets.QGraphicsView(self.centralwidget)
#        self.mainGraphicsView.setGeometry(QtCore.QRect(0, 40, 791, 311))
#        self.mainGraphicsView.setObjectName("mainGraphicsView")
        self.mainComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.mainComboBox.setGeometry(QtCore.QRect(530, 390, 221, 22))
        self.mainComboBox.setObjectName("mainComboBox")
        self.mainPlotSingleChartButton = QtWidgets.QPushButton(self.centralwidget)
        self.mainPlotSingleChartButton.setGeometry(QtCore.QRect(530, 430, 75, 23))
        self.mainPlotSingleChartButton.setObjectName("mainPlotSingleChartButton")
        self.mainPlotAllButton = QtWidgets.QPushButton(self.centralwidget)
        self.mainPlotAllButton.setGeometry(QtCore.QRect(540, 500, 75, 23))
        self.mainPlotAllButton.setObjectName("mainPlotAllButton")
        self.mainSaveSinglePlotButton = QtWidgets.QPushButton(self.centralwidget)
        self.mainSaveSinglePlotButton.setGeometry(QtCore.QRect(630, 430, 75, 23))
        self.mainSaveSinglePlotButton.setObjectName("mainSaveSinglePlotButton")
        self.mainSaveAllButton = QtWidgets.QPushButton(self.centralwidget)
        self.mainSaveAllButton.setGeometry(QtCore.QRect(620, 500, 75, 23))
        self.mainSaveAllButton.setObjectName("mainSaveAllButton")
        self.mainVariablesLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainVariablesLabel.setGeometry(QtCore.QRect(560, 370, 111, 16))
        self.mainVariablesLabel.setObjectName("mainVariablesLabel")
        self.mainImportCSV = QtWidgets.QPushButton(self.centralwidget)
        self.mainImportCSV.setGeometry(QtCore.QRect(10, 370, 121, 23))
        self.mainImportCSV.setObjectName("mainImportCSV")
        self.mainTable = QtWidgets.QTableWidget(self.centralwidget)
        self.mainTable.setGeometry(QtCore.QRect(160, 360, 256, 161))
        self.mainTable.setObjectName("mainTable")
        self.mainTable.setColumnCount(1)
        self.mainTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(0, item)
        self.mainTable.horizontalHeader().setStretchLastSection(True)
        self.mainSelectAll = QtWidgets.QPushButton(self.centralwidget)
        self.mainSelectAll.setGeometry(QtCore.QRect(420, 500, 81, 23))
        self.mainSelectAll.setObjectName("mainSelectAll")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 801, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        mainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(mainWindow)
        self.statusBar.setObjectName("statusBar")
        mainWindow.setStatusBar(self.statusBar)
        self.mainToolBar = QtWidgets.QToolBar(mainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actionImportSession = QtWidgets.QAction(mainWindow)
        self.actionImportSession.setObjectName("actionImportSession")
        self.actionSaveSession = QtWidgets.QAction(mainWindow)
        self.actionSaveSession.setObjectName("actionSaveSession")
        self.actionExit = QtWidgets.QAction(mainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionImportSession)
        self.menuFile.addAction(self.actionSaveSession)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())
        self.mainToolBar.addAction(self.actionImportSession)
        self.mainToolBar.addAction(self.actionSaveSession)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionExit)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "DPT v1.0"))
        self.mainPlotSingleChartButton.setText(_translate("mainWindow", "Plot"))
        self.mainPlotAllButton.setText(_translate("mainWindow", "PlotAll"))
        self.mainSaveSinglePlotButton.setText(_translate("mainWindow", "Save Plot"))
        self.mainSaveAllButton.setText(_translate("mainWindow", "Save All"))
        self.mainVariablesLabel.setText(_translate("mainWindow", "Variables to Plot"))
        self.mainImportCSV.setText(_translate("mainWindow", "Import CSV files"))
        item = self.mainTable.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "File Name"))
        self.mainSelectAll.setText(_translate("mainWindow", "Select All CSVs"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuAbout.setTitle(_translate("mainWindow", "About"))
        self.mainToolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.actionImportSession.setText(_translate("mainWindow", "Import Session"))
        self.actionSaveSession.setText(_translate("mainWindow", "Save Session"))
        self.actionExit.setText(_translate("mainWindow", "Exit"))

